# Generated by Django 4.1.4 on 2022-12-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_product_quantiy_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
