# Generated by Django 4.1.4 on 2022-12-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_quantiy_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'our products'},
        ),
    ]
